### ISSUE TITLE
The live demo is not working

### ISSUE THREAD

**Issue by DannyFeliz** [apertureless/vue-parallax#1]
### Actual Behavior
![screen shot 2016-12-19 at 10 54 38 am](https://cloud.githubusercontent.com/assets/5460365/21317012/a8395c30-c5d9-11e6-87ec-2f40475c5108.png)

**Comment by apertureless** [comment]
Just scroll down bro

**Comment by apertureless** [comment]
Should be fixed now.
The webpack config got an error. It took the generated html file as the template file. So the new generated css and js files got always appended to the old ones. Thats why there were some 404 erros.

However it was never really broken, but I added and indicator that people should scroll down :)
