### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by pwnz22** [apertureless/vue-parallax#10]
Hi all!

Can anyone help to make a parallax exact as [here](http://spb.zoon.ru). 
I'm passing `fixed="true"` to the component but it's getting fixed within all the page.

Thanks.

**Comment by apertureless** [comment]
Hi @pwnz22 

I would try it without the `:fixed="true"` because thats the "real" parallax effekt.
You can edit the `speedFactor` to increase the effect.

**Comment by pwnz22** [comment]
Hi @apertureless 

The `speedFactor ` doesn't make sense. When i increase it the parallax effect ending so early. In those example the image is fixed and when scolling it changes position from top. 
Is it possible to make a similar effect?

Thanks for the fast reply.

**Comment by apertureless** [comment]
I see. Well the example is setting a fixed background image and then translating the top postion based on the scrolling. Thats not really possible with vue-parallaxy, as I am using normal images and not background images. And translating over translate3D.

And I have only the two states, where the images is fixed and where its animated based on the scroll position. Not both. You could try to grab the source and modify it.

You could try to remove the condition https://github.com/apertureless/vue-parallax/blob/master/src/components/Parallax.vue#L62 

And try it with fixed="true"

**Comment by pwnz22** [comment]
Big thanks for helping :)
