### ISSUE TITLE
Doesn't work with Nuxt

### ISSUE THREAD

**Issue by kodekrendel** [apertureless/vue-parallax#12]
I create Nuxt plugin: 

```
import Vue from 'vue'
import Parallax from 'vue-parallaxy'

Vue.use(Parallax)
```
Assign it it nuxt.config.js
```
{src: '~plugins/vue-parallaxy', ssr: false},
```
But nothings work. Code is importing in webpack, no errors, but no work.

**Comment by apertureless** [comment]
`vue-parallaxy`  is **not** a vue plugin. So you can't use `Vue.use()` 
It is simply a component. So after importing it, you can register it as a component and then use it.
