### ISSUE TITLE
It looks horrible on Microsoft Edge.

### ISSUE THREAD

**Issue by CristianH033** [apertureless/vue-parallax#14]
I know it's probably more browser problem than plugin problem but I know there are ways to make it look better on edge.

### Environment
- OS: Windows 10 Creators Update
- vue.js version: 2.x

**Comment by apertureless** [comment]
What do you mean with "It looks horrible" ?

**Comment by HelloWorld017** [comment]
Every slots are blinded and not able to see it. Only white remains.

**Comment by apertureless** [comment]
Should be fixed with 1.0.4
