### ISSUE TITLE
Vue Warn: Error in beforeCreate

### ISSUE THREAD

**Issue by gfelot** [apertureless/vue-parallax#17]
At launch I got this warning : 

```
[Vue warn]: Error in beforeCreate hook: "ReferenceError: document is not defined"

found in

---> <Parallax> at /Users/jjuszczak/Projekte/Privat/vue-parallax/src/components/Parallax.vue
```

And you can find this in the your file ligne 88.

**Comment by apertureless** [comment]
Are you using it in a ssr env ? You need to disable ssr for the component.

**Comment by gfelot** [comment]
yep Nuxt... I have to look how to... but can you explain to me why I have to disable SSR ?

**Comment by apertureless** [comment]
https://nuxtjs.org/guide/plugins/#client-side-only

**Comment by MayyaPakhomova** [comment]
have you decided?

**Comment by apertureless** [comment]
decided what?
