### ISSUE TITLE
Error in beforeCreate hook because of reference to local file

### ISSUE THREAD

**Issue by niklashof** [apertureless/vue-parallax#20]
The current version throws an error:
> [Vue warn]: Error in beforeCreate hook: "ReferenceError: document is not defined" 

This happens because there is a local file referenced:
> <Parallax> at /Users/jjuszczak/Projekte/Privat/vue-parallax/src/components/Parallax.vue

line 3037:

`		beforeCreate: [_t],
		__file: "/Users/jjuszczak/Projekte/Privat/vue-parallax/src/components/Parallax.vue"`

### Environment
- vue-parallax version: 1.0.4

**Comment by apertureless** [comment]
Are you using it in a ssr environment? Like nuxt ?
