### ISSUE TITLE
Reasoning for wide breakpoint default

### ISSUE THREAD

**Issue by Radiergummi** [apertureless/vue-parallax#21]
I just implemented `vue-parallax` and got completely irritated because it refused to work with devTools open, just to discover the breakpoint option and it's default of `(min-width: 968px)`.  
What is the reasoning behind setting it so wide, is it because of performance? Because 968px is a width common for tablets, which should definitely be able to handle the effect...  
This is not meant to be rude, I'm just curious :blush:

**Comment by apertureless** [comment]
Hey @Radiergummi 

to be honest I don't really know why it was set this way. I wrote this component for a client project and open sourced it later on. So might be related to the project requirements back then.

If I find some time, I will look over and maybe change some settings which are a better fit in a more general usecase.

**Comment by Radiergummi** [comment]
Hey @apertureless, I know your struggle 😄  
In the meantime, I've just set the right defaults for my project, so thank you anyway for the plugin.
