### ISSUE TITLE
SSR: false does not work

### ISSUE THREAD

**Issue by jzucadi** [apertureless/vue-parallax#22]
### Expected Behavior
{ src: '~plugins/parallaxy.js', ssr: false } in NUXT yields a "document is not defined error"

### Actual Behavior
{ src: '~plugins/parallaxy.js', ssr: false } does not seem to do anything. I get same results as if I set it to true. 

I realize that you are not responsible for integration with Nuxt, but after reading you help other people on here I am wondering what I am doing wrong. Setting the component to false does nothing. Adding its in the vendor section does nothing. Any other pointers would be greatly appreciated.

**Comment by apertureless** [comment]
Nuxt ships now with the `no-ssr` component which is a wrapper. You could try using it.

**Comment by jzucadi** [comment]
Thank you, I had no idea it was that easy. Kudos on the 60fps, looks stellar
