### ISSUE TITLE
DEMO not workin

### ISSUE THREAD

**Issue by bovas85** [apertureless/vue-parallax#23]
### Expected Behavior
I can see a parallax effect on the first slide

### Actual Behavior
Fixed image scrolling with page, no visible parallax

### Environment
- OS: Write here
Win 10, Chrome and Firefox tested
- NPM version: Write here
n/a
- vue.js version: Write here
n/a
- vue-parallax version: Write here
n/a

**Comment by apertureless** [comment]
@bovas85 
What browser versions are you using?
I've tested it on windows 7 with 

- chrome 63 
- chrome canary 66
- firefox 56 

and all are working fine.

**Comment by bovas85** [comment]
I just checked, I'm using an iMac 2017 with latest firefox and it works. 
I think I didn't notice any movement last time when I checked but that's probably due to the very minimal movement the parallax is set to.
