### ISSUE TITLE
Bg image leaving white space inside the div

### ISSUE THREAD

**Issue by bovas85** [apertureless/vue-parallax#24]
### Expected Behavior
Bg image doesn't leave white space on top

### Actual Behavior
![screen shot 2018-01-29 at 15 21 35](https://user-images.githubusercontent.com/16958684/35518010-1e16373e-0508-11e8-9040-b07a6778c6c7.jpg)

### Environment
- OS: iMac Sierra High latest
- npm: 5.6.0
- vue.js 2.5.3
- vue-parallax version: latest from npm

**Comment by bovas85** [comment]
This is related to a missing direction prop. 
The code seems to not take that into consideration.

Can you check my pull request?

**Comment by apertureless** [comment]
Thanks for the pr. Will check it later.

**Comment by apertureless** [comment]
Should be fixed in 1.1.0

**Comment by bovas85** [comment]
Cheers

**Comment by bovas85** [comment]
It's actually broken now, will need to retest
