### ISSUE TITLE
PR unmerged

### ISSUE THREAD

**Issue by bovas85** [apertureless/vue-parallax#27]
### Expected Behavior
1.1.0 contains latest PR with fixed direction computed value

### Actual Behavior
1.1.0 is same as 1.0.4

### Environment
- OS: Write here
- NPM version: Write here
- vue.js version: Write here
- vue-parallax version: Write here

**Comment by bovas85** [comment]
Maybe you forgot to release the new dist ?

**Comment by apertureless** [comment]
Oh weird. 
Will check on this.

**Comment by apertureless** [comment]
Should be fixed now.
