### ISSUE TITLE
Not working in SSR mode

### ISSUE THREAD

**Issue by ram-you** [apertureless/vue-parallax#3]
### Expected Behavior
Working server side

### Actual Behavior

Not working

### Environment
- OS: Ubuntu 14.04
- NPM version: 7.4
- vue.js version: 2.1.8
- vue-parallax version:0.1.1

Reference Error: window is not defined

**Comment by apertureless** [comment]
Hello @ram-you 

well I can't tell without seeing your code, but it seems that you're trying to render the parallax code on the server. This can't work, as node.js does not have a window object.

And it does not make really sense to render the parallax stuff server sided. It is client side code.

You could try to load the parallax component only on the client side,
or try to mock a fake window object.
