### ISSUE TITLE
Layer multiple instances of <paralllax></paralllax> on top of one another to create a cool layering effect?

### ISSUE THREAD

**Issue by gilgameshskytrooper** [apertureless/vue-parallax#30]
# Might not actually be a bug (just wondering if a certain thing is possible to do in vue-parallax)

Right now, I’m trying to layer together about 6 images to have a cool effect (whereby further assets scroll slower than closer ones).

I can’t seem to figure out how to layer all the parallax windows on top of one another (without setting position to absolute, which obviously breaks the parallax plugin).

Any help would be mightily appreciated.

Thanks,

**Comment by apertureless** [comment]
Hey @gilgameshskytrooper 

Mhh I think this is not really possible right now. Because this use case was never intented.

**Comment by gilgameshskytrooper** [comment]
cool. thanks
