### ISSUE TITLE
Undefined shows up instead of actual Image

### ISSUE THREAD

**Issue by andrerfneves** [apertureless/vue-parallax#4]
### Expected Behavior

Image tag gets transcribed into `slot` and parallax effect takes place

### Actual Behavior

I receive a `undefined` tag inside of my HTML. Images below as follow. Image asset exists and path is correct.

### Environment
- OS: macOS Sierra 10.12
- NPM version: 3.8.6
- vue.js version: 2.1.8
- vue-parallax version: 0.1.1

<img width="1270" alt="screen shot 2017-01-06 at 10 36 29 am" src="https://cloud.githubusercontent.com/assets/2574011/21722855/5f83431c-d3fc-11e6-835c-ae9169d78762.png">

<img width="761" alt="screen shot 2017-01-06 at 10 36 39 am" src="https://cloud.githubusercontent.com/assets/2574011/21722867/69dc59fc-d3fc-11e6-90b2-a46aa31382fb.png">

Any clue why this could be happening?

**Comment by apertureless** [comment]
Any errors in the js console / vue devtools ?

**Comment by andrerfneves** [comment]
<img width="1278" alt="screen shot 2017-01-06 at 10 47 20 am" src="https://cloud.githubusercontent.com/assets/2574011/21723195/8e1d4230-d3fd-11e6-935c-94a17bb64b9f.png">

Console is also clean.

I'm running Vue 2.1.8 actually. My mistake.

**Comment by apertureless** [comment]
Can you provide a minimal repo / jsbin for reproduction?

**Comment by andrerfneves** [comment]
Yeah sure. give me a second @apertureless

**Comment by andrerfneves** [comment]
@apertureless, sorry for the delay.

https://github.com/andrerfneves/test-repo-parallax
Here's a minimal test repo for the issue I encounter in Vue Parallax package.
There's a simple IMG tag that works, and then there's the parallax that fails.

Let me know if you need explanation/clarification.
Thanks

![screen shot 2017-01-09 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/2574011/21780396/6cff8daa-d679-11e6-802d-bc69133f9c60.png)

**Comment by apertureless** [comment]
Thanks, will look into it.

**Comment by andrerfneves** [comment]
Any updates @apertureless? Could this be incompatibility with Vue 2.1.8?

**Comment by apertureless** [comment]
Should be fixed in `0.1.2.`

**Comment by andrerfneves** [comment]
Great stuff. Appreciate it @apertureless
