### ISSUE TITLE
change image starting position to top

### ISSUE THREAD

**Issue by antonioreyna** [apertureless/vue-parallax#7]
hello, how can i change the image position?

**Comment by apertureless** [comment]
Don't really understand your question.

**Comment by antonioreyna** [comment]
i copy the styles and changed this

```
 @include object-fit(cover, bottom);
```

is that the way to go?

**Comment by apertureless** [comment]
Oh now I understand.
Yeah the object fit must be changed in the css.

The styles are relevant for the behavior, to give you as much control as possible.
Thats why you can pass the relevant css classes as props. So you can style them the way you want.

However the masthead class, which contain the image, has always a height of 120%.  The 20% are nessasary for the parallax effect. Thats why you not always see a perfect crop of your image.

**Comment by antonioreyna** [comment]
great! thank you!
